# Math 314 Lab 2

## Polynomial Interpolation

**Name:**

See companion PDF on the course website for background and instructions.

## Exercise 1

Attach hand computation or enter your response here.

## Exercise 2

Attach hand computation or enter your response here.

## Exercise 3

Attach hand computation or enter response here.

## Exercise 4

Suppose we want to solve $Ax = b$ where $b$ is given and $A$ is a matrix.

The Julia notation for this works as follows:

1) Define the matrix `A`
2) Define the vector `b`
3) Use the backslash operator: `x = A \ b`

That last line is a little funny looking.  It means "Go solve $Ax=b$ and assign the results to a variable called `x`". 

The backslash operator is a bit of a "black box".  Depending on the the shape and structure of the matrix `A`, it chooses a suitable algorith.  In the generic case of a square matrix it uses a technique called $LU$ factorization, which we will discuss later in the class.  For now, we will just use the backslash operator without knowing how it goes about its business.

Here's an example.

In [2]:
A = [ 4 2; 2 -3]

2×2 Matrix{Int64}:
 4   2
 2  -3

In [7]:
b = [-4; -18]

2-element Vector{Int64}:
  -4
 -18

In [10]:
x =  A \ b

2-element Vector{Float64}:
 -3.0
  4.0

We can verify that this worked:

In [11]:
A*x - b

2-element Vector{Float64}:
 0.0
 0.0

### Now your turn:

Use Julia to solve the equations you wrote down in Exercise 3 to determine `m` and `b`.

In [ ]:
# Data points
x_data = [0.2, 0.8]
y_data = [0.7, -0.4]


In [118]:
# Code to set up and solve the equations goes here.

When you solve the equations, the results will be packed in a vector.  Here's some handy syntax for extracting elements of a vector into variables.  If `x` is a 2-dimensional vector,
```
b, m = x
```
will assign `b=x[1]` and `m=x[2]`.

Use this notation to extract the slope and y-intercept. Note that your ordering of `m` and `b` might be different from mine

In [115]:
# Extract `m` and `b` here.


## Exercise 5

Given your values of `m` and `b` that you just computed, make a plot of the following:

1) The two data points used to determine the line.
2) The line going through them, via your `m` and `b`.

Your $x$ coordinate in your plot should run from 0 to 1.

In [117]:
# Plotting code goes here.

## Exercise 6

Data points collected as a matrix `p`.  To get point $p_k$, use `p[:,k]`. To get all the `x` coordinates, use `p[1,:]`.  You can access the `y` coordinates similarly.

In [120]:
x_data = [-1, 3, 5]
y_data = [ 1.5, 32.2, -42.6 ];

### Hand computation
By hand, record the system of equations to solve and convert the system to a matrix system $Ax = b$ to solve, where $A$ and $b$ are known.


### Contruct matrix with Julia

In [40]:
# Commands go here to:
# 1) Create the matrix `A`
# 2) Create the right hand side `b`
# 3) Solve for the coefficients `c` using the backslash operator.


Now plot your solution (i.e. the quadratic) along with the three data points. If you were successful, you should see your quadratic pass through all three data points.  For your plot, use the range $-2 \le x \le 8$ for the $x$ coordinate.

In [41]:
# Commands to generate plot go here.

## Exercise 7

If you have 7 data points $(x_n,y_n)$, with all of the $x_n$'s different, these uniquely determine a polynomial of some order.  What is the order? 


**Your response goes here**

## Exercise 8

We will represent polynomials using a vector of coefficients. For example,
`c = [2, -3]` will represenet $p(x) = 2 - 3x$ and `c=[4, 2, -6]` will represent $p(x) = 4 + 2x - 6x^2$.  

We want to conveniently evaluate polynomials given a vector of coefficients `c` and a vector `x` of input values.  Write a function `poly_eval` that receives
a vector `c` of coefficients and a vector `x=[x_1,...,x_k]` of $x$-coordinates, and that returns `[p(x_1),...,p(x_k)]`, where $p(x)$ is the polynomial
represented by the coefficients.

I've started the code for you.  Your job is to fill in the body of the main loop.

In [55]:
function poly_eval(c, x)

    # Make a vector of length 
    y = zeros(length(x))

    # Set all of `y` to the single value `c[1]`, the constant coefficent.

    y .= c[1]

    # For each higher term, add on an additional amount to `y`    
    for k in 2:length(c)
        # Your update goes here:
        y = y ## fill this in

        # Be careful! The first time through the loop, the coefficient
        # you want is c[2], but this is associated with a power x^1,
        # not x^2.
    end

    return y
end

poly_eval (generic function with 1 method)

Test that your code works with `c = [ 1 2 -2]` and `x = [0.2, 0.3]`

In [ ]:
poly_eval([1, 2, -2], [ 0.2, 0.3])

In [57]:
# If your code is correct, the results should be the same as:
[1 + 2*0.2 - 2*0.2^2, 
    1 + 2*0.3 - 2*0.3^2 ]

2-element Vector{Float64}:
 1.3199999999999998
 1.4200000000000002

## Exercise 9

The function `vandermonde` below is nearly finished.  It is supposed
to receive a vector of `x` coordinates and return the associated Vandermonde matrix
described in the Lab 2 PDF.  The only thing that needs completing is the body of the inner loop, starting with the comment `# Your job:`.

In [60]:
function vandermonde(x)
    # Polynomial order depends on number of
    # data points. Two points determine a first order polynomial.
    # Three points determine a quadratic (second order)
    n = length(x) - 1

    # Make an all zero matrix that is the right shape.
    A = zeros( n+1, n+1 )

    # Now update the entries.
    for i = 1:n+1 # for each row (each data point)
        for j = 1:n+1 # for each column

            # Your job:
            #            
            # Update A[i,j] here

        end
    end
    
    return A
end

vandermonde (generic function with 1 method)

Test that your `vandermonde` works by computing
`vandermonde([2,3,4])`

In [61]:
vandermonde([2,3,4])

3×3 Matrix{Float64}:
 1.0  2.0   4.0
 1.0  3.0   9.0
 1.0  4.0  16.0

If your code is successful, you should see:
```
3×3 Matrix{Float64}:
 1.0  2.0   4.0
 1.0  3.0   9.0
 1.0  4.0  16.0
```


## Exercise 10

For this exercise you will fit a 6th order polynomial
to 7 data points and plot the resulting polynomial along with
the points to verify that your work is successful.

The data points:

In [80]:
p = [ 1 2 4 5 8 9 11
      4 -1 7 -3 1 -10 3 ]
x_data = p[1,:];
y_data = p[2,:];

Now solve for the coefficients.

In [ ]:
# Code here to 
# 1) Build Vandermonde matrix A associated with x_data
# 2) Solve for coefficients c satisfying A c = y_data


Now generate a plot of your polynomial and the 7 data points.

* Your $x$ coordinate should range from $0.5$ to $11.5$, e.g. `x = Array(LinRange(0.5, 11.5, 1000))`
* You should use `poly_eval(c, x)` to generate the associated `y` coordinates.
* Your plot should also include the data points used to generate the polynomial.

If everything has worked, your data points should lie on the polynomial.

In [81]:
# Plotting code goes here.

## Challenge: Exercise 11

In this optional problem we are going to compute a polynomial approximation of cosine.


In [112]:
x_data = [0, pi/6, pi/4, 2*pi/6, pi/2, 2*pi/3, 3*pi/4, 5*pi/6, pi];
y_data = cos.(x_data);

Generate the Vandermonde matrix. The tricky part is that we
only want an even order polynomial, so instead of `vandermonde(x_data)`,
use `vandermonde(x_data.^2)`.  

In [113]:
c = vandermonde(x_data.^2) \ y_data

9-element Vector{Float64}:
  1.0
 -0.4999999999998913
  0.041666666665880286
 -0.0013888888869664825
  2.4801585186172914e-5
 -2.755720208447791e-7
  2.087328015499349e-9
 -1.141469609312696e-11
  4.3167540881700634e-14

Generate a plot of the polynomial interpolant along with the 9 data points for $0\le x \le \pi$.

In [111]:
# Plotting code goes here.

Now also plot the difference between $\cos(x)$ and the polynomial interpolant,
again for $0\le x\le \pi$.

In [114]:
# Plotting code goes here.